const movieData =[
    {
        "title" : "Descendants Of The Sun",
        "korean" : "태양의 후예",
        "star": "Starring : Song Joong-ki, Song Hye-kyo, Jin Goo, Kim Ji-won",
        "mdlrate": "MDL Rating : 8.7/10",
        "personalrate": "Personal Preference : 10/10",
        "year": "Released Year : 2016",
        "genre": "Genres: Action, Comedy, Romance, Melodrama",
        "poster": "https://1.bp.blogspot.com/-ggxxXMZcWwk/VtZJNRW7QvI/AAAAAAAAAcs/x8CBIF_IsYQ/s1600/Descendants-of-the-Sun-03.jpg",
        "mdllink" : "https://mydramalist.com/10904-descendants-of-the-sun",
        "trailer" : "https://www.youtube.com/watch?v=3Fyrt0qByOQ",
        "summary" : "Kang Mo Yeon is a pretty and assertive woman who works as a cardiothoracic surgeon at Haesung Hospital. She isn't afraid to admit her mistakes and believes that capability overrides whatever connections you have. However, she is soon faced with the reality that she cannot advance with just capability. Her life is forever changed when she encounters Yoo Shi Jin, the Captain and team leader of Alpha Team who cares more about protecting anybody in need of help as well as his country, even if it goes against the order of his superiors. This drama will tell of how they both bond together in a time of war and overcome the odds against them."
    },
    {
        "title" : "Moon Lovers : Scarlet Heart Ryeo ",
        'korean' : "달의 연인 - 보보경심",
        "star": "Starring : Lee Joon-gi, IU, Kang Ha-neul",
        "mdlrate": "MDL Rating : 8.7/10",
        "personalrate": "Personal Preference : 10/10",
        "year": "Released Year : 2016",
        "genre": "Genres: Historical, Romance, Melodrama",
        "poster": "https://image.tmdb.org/t/p/original/pjdPGHqUe60ZGQJR1TItVNaV4it.jpg",
        "mdllink" : "https://mydramalist.com/15999-moon-lovers-scarlet-heart-ryeo",
        "trailer" : "https://www.youtube.com/watch?v=2ljxyaAIphc",
        'summary' : "When a total eclipse of the sun takes place, Go Ha Jin is transported back in time to the start of the Goryeo Dynasty of Korea during King Taejo's rule. She wakes up in the body of the 16-year-old Hae Soo and finds herself living in the house of the 8th Prince Wang Wook, who is married to Hae Soo's cousin. She soon befriends several of the princes and meets the ostracized 4th Prince, Wang So. Although knowing she should not get involved in palace intrigues over the succession to the throne, she inadvertently becomes a pawn in the struggle, as several of the Princes fall in love with her."
    },
    {
        "title" : "Fight For My Way ",
        "korean" : "쌈 마이웨이",
        "star": "Starring : Lee Joon-gi, IU, Kang Ha-neul",
        "mdlrate": "MDL Rating : 8.5/10",
        "personalrate": "Personal Preference : 9.5/10",
        "year": "Released Year : 2017",
        "genre": "GGenres: Business, Comedy, Romance, Sports ",
        "poster": "https://i.pinimg.com/originals/e0/ed/bb/e0edbb15022d9c9a04e6af152bab6576.jpg",
        "mdllink" : "https://mydramalist.com/22472-fight-for-my-way",
        "trailer" : "https://www.youtube.com/watch?v=tbRDt_yzwBA",
        'summary' : "Can you still go after your dreams without the right background? Ko Dong Man has always dreamed of becoming famous as a taekwondo athlete but now works as a contract employee in a mundane job. His bickering longtime friend, Choi Ae Ra, aspires to become a television anchor but works instead at the information desk of a department store. Their friends, Kim Joo Man and Baek Seol Hee have been dating for six years but face a new threat to their relationship. Can the four friends achieve their individual dreams despite having “third-rate” qualifications?"
    },
    {
        "title" : "What's Wrong With Secretary Kim ",
        "korean" : "김비서가 왜 그럴까",
        "star": "Starring : Park Seo-joon, Park Min-young",
        "mdlrate": "MDL Rating : 8.5/10",
        "personalrate": "Personal Preference : 9/10",
        "year": "Released Year : 2018",
        "genre": "Genres: Friendship, Business, Comedy, Romance",
        "poster": "https://img.reelgood.com/content/show/900f5fc3-b513-410e-b374-af0492794c85/poster-780.jpg",
        "mdllink" : "https://mydramalist.com/27885-why-secretary-kim",
        "trailer" : "https://www.youtube.com/watch?v=e43gG2nC8Cg",
        'summary' : 'The series revolves around the narcissistic Lee Young Joon, the vice president of a company run by his family. He is very self-absorbed and thinks highly of himself, so much that he barely acknowledges the people around him. Lee Young Joon has a capable and patient secretary Kim Mi So who has remained by his side and worked diligently for 9 years without any romantic involvement. However, Mi So now wants to set her life & focus on herself so when she decides to resign from her job, hilarious misunderstandings ensue. After 9 years of their strictly-workplace relationship, can it now develop in something more?'
    },
    {
        "title" : "Hotel Del Luna ",
        "korean" : "호텔 델루나",
        "star": "Starring : Park Seo-joon, Park Min-young",
        "mdlrate": "MDL Rating : 8.7/10",
        "personalrate": "Personal Preference : 9.5/10",
        "year": "Released Year : 2019",
        "genre": "Genres: Horror, Comedy, Romance, Fantasy ",
        "poster": "https://0.soompi.io/wp-content/uploads/2019/06/30195530/Hotel-Del-Luna1.jpg",
        "mdllink" : "https://mydramalist.com/32925-hotel-del-luna",
        "trailer" : "https://www.youtube.com/watch?v=5eaITwAw-Pg",
        "summary" : "Nestled deep in the heart of Seoul’s thriving downtown sits a curious hotel, the like of which no one has ever seen before. Old beyond measure, the building has stood for millennia, an ever-present testament to the fact that things are not always what they seem. Running this hotel is Jang Man Wol, a greedy, suspicious soul who has spent the past thousand years acting as the establishment’s CEO. Bound to the hotel by a deity who keeps her there to save her from going berserk and self-destruction with rage, hatred and thirst for revenge. Her only hope of escape is if she could let go of her resentment and hatred, and find love. Trapped in her resentment for a betrayal, Man Wol is doomed to spend all of the eternity running this odd establishment, catering to the needs of the most peculiar clientele."
    },
    {
        "title" : "True Beauty ",
        'korean' : "여신강림",
        "star": "Starring : Cha Eun-woo, Moon Ga-young, Hwang In-yeop, Park Yoo-na",
        "mdlrate": "MDL Rating : 8.4/10",
        "personalrate": "Personal Preference : 8.5/10",
        "year": "Released Year : 2020",
        "genre": "Genres: Comedy, Romance, Youth, Drama",
        "poster": "https://image.kpopmap.com/2020/11/true-beauty-tvn-official-posters-2.jpg",
        "mdllink" : "https://mydramalist.com/38627-true-beauty",
        "trailer" : "https://www.youtube.com/watch?v=KsYzLsEsRaU",
        'summary' : 'True Beauty is a romantic comedy about a high school girl Lim Ju Gyeong, who rises to pretty girl fame after she masters the art of make-up from YouTube. She turns into a goddess because of her makeup skills, but would rather die than reveal her bare face to anyone. It tells her love story with the only boy that saw her without makeup, Lee Su Ho. Lee is an attractive and handsome boy who appears cold because of his dark past but is actually very caring. They grow when they meet each other sharing their secrets and finding love with each other, but can Su Ho make Ju Gyeong find her true beauty?'
    },
    {
        "title" : "Crash Landing On You",
        "korean" : "사랑의 불시착",
        "star": "Starring : Hyun Bin, Son Ye-jin, Seo Ji-hye, Kim Jung-hyun",
        "mdlrate": "MDL Rating : 9/10",
        "personalrate": "Personal Preference : 9/10",
        "year": "Released Year : 2019",
        "genre": "Genres: Military, Comedy, Romance, Political",
        "poster": "https://i1.wp.com/www.kdramapal.com/wp-content/uploads/2020/02/Crash-Landing-On-You-Poster-2.jpg?ssl=1",
        "mdllink" : "https://mydramalist.com/35729-emergency-lands-of-love",
        "trailer" : "https://www.youtube.com/watch?v=eXMjTXL2Vks",
        'summary' : "After getting into a paragliding accident, South Korean heiress Yoon Se Ri crash lands in North Korea. There, she meets North Korean army officer Ri Jung Hyuk, who agrees to help her return to South Korea. Despite the tension between their countries, the two of them start falling for one another."
    },
    {
        "title" : "Uncontrollably Fond ",
        "korean" : '함부로 애틋하게',
        "star": "Starring : Kim Woo-bin, Bae Suzy, Im Joo-hwan, Im Ju-eun",
        "mdlrate": "MDL Rating : 8.1/10",
        "personalrate": "Personal Preference : 8.5/10",
        "year": "Released Year : 2016",
        "genre": "Genres: Comedy, Romance, Drama, Melodrama",
        "poster": "https://curcol.co/wp-content/uploads/2016/07/poster_uncontrollablyfond.jpg",
        "mdllink" : "https://mydramalist.com/15320-uncontrollably-fond",
        "trailer" : "https://www.youtube.com/watch?v=2BhKaOi5OJ0",
        'summary' : 'People change but can the heart adapt? Sin Joon Young and No Eul were  in love in their younger days. But uncontrollable circumstances separated them and they went their separate ways. Joon Young is now a superstar actor and singer, while No Eul became a producer-director of documentaries. When their paths cross again years later, Joon Young discovers that No Eul is now a very different person than he remembered — materialistic and willing to do anything to get ahead. Is there any hope for Joon Young and No Eul to rekindle their past relationship?'
    },
    {
        "title" : "It's Okay To Not Be Okay ",
        'korean' : '사이코지만 괜찮아',
        "star": "Starring : Kim Soo-hyun, Seo Yea-ji, Oh Jung-se",
        "mdlrate": "MDL Rating : 9/10",
        "personalrate": "Personal Preference : 8/10",
        "year": "Released Year : 2020",
        "genre": "Genres: Psychological, Comedy, Romance, Drama",
        "poster": "https://img.reelgood.com/content/show/542095b0-b06d-4ece-a535-cda80be17042/poster-780.jpg",
        "mdllink" : "https://mydramalist.com/49865-psycho-but-it-s-okay",
        "trailer" : "https://www.youtube.com/watch?v=50ek4HQo0Bc",
        'summary' : 'Moon Gang Tae is a community health worker at a psychiatric ward who was blessed with everything including a great body, smarts, ability to sympathize with others, patience, ability to react quickly, stamina, and more. Meanwhile, Ko Moon Young is a popular writer of children’s literature who, due to suffering from an antisocial personality disorder, seems extremely selfish, arrogant, and rude.'
    },
    {
        "title" : "W: Two Worlds ",
        'korean' : '더블유',
        "star": "Starring : Han Hyo-joo, Lee Jong-suk",
        "mdlrate": "MDL Rating : 8.5/10",
        "personalrate": "Personal Preference : 8/10",
        "year": "Released Year : 2016",
        "genre": "Genres: Thriller, Comedy, Romance, Fantasy",
        "poster": "https://i.pinimg.com/originals/07/cf/bd/07cfbdef5e0102201f5c449591bc3ff3.jpg",
        "mdllink" : "https://mydramalist.com/16589-w",
        "trailer" : "https://www.youtube.com/watch?v=iFyxffHNwvE",
        'summary' : "Oh Sung Moo, the father of cardiothoracic surgeon Oh Yeon Joo, mysteriously goes missing while writing the last chapter of his webtoon 'W'. Yeon Joo goes to his office looking, but a hand from his monitor suddenly pulls her in, and she finds herself on the rooftop of a building, next to a man bloodied. She manages to save the person, only to realize that he is Kang Cheol, the main character of her father's webtoon. Yeon Joo later discovers she can only enter and leave the webtoon depending on Kang Cheol's feelings."
    },
    {
        "title" : "I'm Not a Robot ",
        'korean' : '로봇이 아니야',
        "star": "Starring : Yoo Seung-ho, Chae Soo-bin",
        "mdlrate": "MDL Rating : 8.5/10",
        "personalrate": "Personal Preference : 8.5/10",
        "year": "Released Year : 2018",
        "genre": "Genres: Comedy, Romance, Drama, Sci-Fi",
        "poster": "https://tupersonajefavorito.com/wp-content/uploads/2018/11/i%C2%B4m-not-a-robot-1.jpg",
        "mdllink" : "https://mydramalist.com/24351-im-not-a-robot",
        "trailer" : "https://www.youtube.com/watch?v=BP1uofuww1w",
        'summary' : "Kim Min Kyu is the largest shareholder of a financial company. He suffers from a 'human allergy', preventing him from normal interactions with other people. He becomes interested in a robotic project named Aji-3 created by the Santa Maria robotic team. The team is headed by Hong Baek Gyun,  inventor of Aji-3 and world-renowned robotics professor. He modeled Aji-3 after his ex-girlfriend, Jo Ji Ah, a struggling inventor that also works as a personal shopper to make ends meet.  Just when Kim Min Kyu wants to test the robot, an accident causes the malfunction of the robot's battery. Hong Baek Gyun begs Jo Ji Ah to take the place of Aji-3 and pretend to be the robot so they can get funding from Kim Min Kyu. But, Aji-3 becomes the closest thing that the lonely Min Kyu has to real contact with another person."
    },
    {
        "title" : "Pinocchio ",
        'korean' : '피노키오',
        "star": "Starring : Lee Jong-suk, Park Shin-hye",
        "mdlrate": "MDL Rating : 8.4/10",
        "personalrate": "Personal Preference : 8/10",
        "year": "Released Year : 2015",
        "genre": "Genres: Mystery, Comedy, Romance",
        "poster": "https://th.bing.com/th/id/R.ec925ba9244b5867d5058ea5456116ae?rik=LaBmf1yUTSTejg&riu=http%3a%2f%2fwww.hancinema.net%2fphotos%2ffullsizephoto516847.jpg&ehk=fSkcoU%2fFPpaCnNliAKNDtyoURoKWRMOoddLBXu%2f62so%3d&risl=&pid=ImgRaw&r=0",
        "mdllink" : "https://mydramalist.com/11074-pinocchio",
        "trailer" : "https://www.youtube.com/watch?v=-e16YT2_oQw",
        "summary" : "The idealistic Choi In Ha has her work cut out for her when she becomes a broadcast journalist, especially when she suffers from a condition known as “Pinocchio syndrome,” which makes her break out into hiccups whenever she tells a lie. Her rookie colleagues include Choi Dal Po, whose shabby appearance masks his true eloquence and sharp memory; Seo Bum Jo, a wealthy heir who has had everything handed to him in life; and Yoon Yoo Rae, whose fangirl knowledge comes in handy in covering the news. The 20-something newbie reporters pursue justice as they try to discover themselves in the process."
    }
]

export default movieData;